kind: pipeline
type: kubernetes
name: Build bardly app and dependencies

steps:
  - name: build bardly-api node app
    image: plugins/docker
    settings:
      registry: 'harbor-bitnami.default'
      repo: 'harbor-bitnami.default/homelab/bardly-api'
      username: stewart
      password: stJ0hnstuHARBOR #todo: replace with secret
      dockerfile: ./Dockerfile
      debug: true
      launch_debug: true
      insecure: true
      use_cache: false

  - name: build couchdb
    image: plugins/docker
    settings:
      registry: 'harbor-bitnami.default'
      username: stewart
      password: stJ0hnstuHARBOR #todo: replace with secret
      repo: 'harbor-bitnami.default/homelab/couchdb'
      dockerfile: ./Dockerfile-couchdb
      debug: true
      launch_debug: true
      insecure: true

  - name: build redis
    image: plugins/docker
    settings:
      registry: 'harbor-bitnami.default'
      username: stewart
      password: stJ0hnstuHARBOR #todo: replace with secret
      repo: 'harbor-bitnami.default/homelab/redis'
      dockerfile: ./Dockerfile-redis
      debug: true
      launch_debug: true
      insecure: true

  - name: deploy all
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: drone_k8s_server
      kubernetes_cert:
        from_secret: drone_k8s_cert
      kubernetes_token:
        from_secret: drone_k8s_token
    commands:
      - kubectl apply -f redisdb-service.yaml --namespace=bardly
      - kubectl apply -f couchdb-service.yaml --namespace=bardly
      - kubectl apply -f bardly-api-manifest.yaml --namespace=bardly
