kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: stewart
      password: stJ0hnstuHARBOR #todo: replace with secret
      repo: harbor-bitnami/homelab/bardly-api
      dockerfile: Dockerfile
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
