kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: stewart
      password: stJ0hnstuHARBOR #todo: replace with secret
      repo: 192.168.0.199:32443/homelab/bardly-api
      dockerfile: Dockerfile
