apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bardly-api
  name: bardly-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bardly-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bardly-api
    spec:
      containers:
      - image: bardly-api
        name: bardly-api
        imagePullPolicy: Never
        resources: {}
        ports:
         - containerPort: 9000
      initContainers:
      - name: init-couchdb
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup couchdb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for couchdb; sleep 2; done"]
      - name: init-redisdb
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup redisdb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redisdb; sleep 2; done"]

status: {}
