apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bardly-api
  name: bardly-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bardly-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bardly-api
    spec:
      containers:
      - image: bardly-api
        name: bardly-api
	imagePullPolicy: Never
        resources: {}
	ports:
	 - containerPort: 9000
status: {}
