apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
    app: bardly-api-couch
  name: couchdb
spec:
  ports:
  - name: "5984"
    port: 5984
    targetPort: 5984
  selector:
    io.kompose.service: couchdb
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
    app: bardly-api-couch
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: couchdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-dev.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb
        app: bardly-api-couch
    spec:
      containers:
        - env:
            - name: COUCHDB_PASSWORD
              value: -pbkdf2-7ac683f7c830ce579c7d8e11379273c217d001a9,f089da8c612a207145f486ebf3761cd7,10
            - name: COUCHDB_USER
              value: admin
          image: mycouchdb-1:latest
          imagePullPolicy: IfNotPresent
          name: couchdb
          ports:
            - containerPort: 5984
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/var/lib/couchdb
              name: couchdb-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: couchdb-claim0
          persistentVolumeClaim:
            claimName: couchdb-claim0
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb-claim0
    app: bardly-api-couch
  name: couchdb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
