#FROM couchdb:1.6.1
FROM klaemo/couchdb:1.6.1

RUN sed -e '/^\[admins\]$/a admin=-pbkdf2-a68a0db1e18b9d57c462271163124cd93ef08c9c,2ad519368d7fe05d96110e292d81d8ef,10\n' -i /usr/local/etc/couchdb/local.ini
RUN sed -e '/^\[couch_httpd_auth\]$/a require_valid_user = true\n' -i /usr/local/etc/couchdb/local.ini
RUN sed -e 's/^;WWW-Authenticate/WWW-Authenticate/' -i /usr/local/etc/couchdb/local.ini

EXPOSE 5984
