version: '2'
services:
  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - "./app:/src/app"
    ports:
      - "8181:8080"
    links:
      - "db:redis"
      - "couchdb:mycouchdb-1"

  db:
    image: redis

  couchdb:
    build:
      context: .
      dockerfile: Dockerfile-couchdb
    # ports:
    #   - "5984:5984"
    image: mycouchdb-1:latest
