FROM datadog/docker-dd-agent:latest-alpine

# Set your API key
# Dont think this is necessary as set via compose variables
# RUN sed -i -e"s/^.*api_key:.*$/api_key: 20b3ad2b6be21daf2a90bb6b4acecdb7/" /etc/dd-agent/datadog.conf
