version: '2'
services:
  redisdb:
    ports:
      - "6379:6379" #enabled for local debugging
    image: redis
    volumes:
      - "./web-volume/redis:/data"

  couchdb:
    build:
      context: .
      dockerfile: Dockerfile-couchdb
    ports:
      - "5984:5984" #enabled for local debugging
    image: mycouchdb-1:latest
    volumes:
      - "./web-volume/couchdb:/usr/local/var/lib/couchdb"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=-pbkdf2-7ac683f7c830ce579c7d8e11379273c217d001a9,f089da8c612a207145f486ebf3761cd7,10

#  web:
#    build:
#      context: .
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
##    volumes:
##      - "./app:/src/app"
#    ports:
#      - "9000:9000"
#      - "9615:9615" #expose pm2 --web monitor port
#    links:
#      - "redisdb:redis"
#      - "couchdb:mycouchdb-1"
##    volumes:
##      - "./web-volume/web:/app/couchdb"

