version: '2'
services:
  redisdb:
    image: redis

  couchdb:
    build:
      context: .
      dockerfile: Dockerfile-couchdb
    ports:
      - "5984:5984"
    image: mycouchdb-1:latest

  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
#    volumes:
#      - "./app:/src/app"
    ports:
      - "9000:9000"
    links:
      - "redisdb:redis"
      - "couchdb:mycouchdb-1"
