version: '2'
services:
  redisdb:
#    ports:
#      - "6379:6379" #enabled for local debugging
    image: redis
    volumes:
      - "./web-volume/redis:/data"

  couchdb:
    build:
      context: .
      dockerfile: Dockerfile-couchdb
    ports:
      - "5984:5984" #enabled for local debugging
    image: mycouchdb-1:latest
    volumes:
      - "./web-volume/couchdb:/usr/local/var/lib/couchdb"

  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
#    volumes:
#      - "./app:/src/app"
    ports:
      - "9000:9000"
      - "9615:9615" #expose pm2 --web monitor port
    links:
      - "redisdb:redis"
      - "couchdb:mycouchdb-1"
#    volumes:
#      - "./web-volume/web:/app/couchdb"
    image: writeon_web
    environment:
      - DATADOG_HOST=datadog # used by the web app to initialize the Datadog library
      - COUCH_REPLICATION_SOURCE=foo
      - COUCH_REPLICATION_TARGET=bar

  #datadog integration
  datadog:
      build:
        context: .
        dockerfile: Dockerfile-dogstatd
      links:
       - web # ensures that the web app can send metrics
      environment:
       - API_KEY=20b3ad2b6be21daf2a90bb6b4acecdb7
       - DD_HOSTNAME=compose-datadog-alpine-prod
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /proc/mounts:/host/proc/mounts:ro
       - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
