apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
  labels:
    app: nfs-test-volume
spec:
  containers:
    - name: mynginx
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        subPath: "nginx/html"
        name: nfs-test
  volumes:
    - name: nfs-test
      persistentVolumeClaim:
        claimName: nfs-test-volumeclaim
