apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-volumeclaim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 8Gi
status: {}

