apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test-volume
  labels:
    app: nfs-test-volume
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.0.197
    path: /data/media-8tb/k8s/volumes
