---
#Setup docker config so ufw rules take affect. Tested and Works with Docker version 17.05.0-ce, build 89658be
#  # not sure if these 2 tasks are still required. It might add a duplicate line if it already exists as ACCEPT
#  - name: Test for DEFAULT_FORWARD_POLICY in docker
#    shell: "grep 'DEFAULT_FORWARD_POLICY=\"DROP\"' /etc/default/docker"
#    register: test_default_forward_policy
#    failed_when: "test_default_forward_policy.rc == 2"
#    changed_when: false
#    become: true
#
#  - name: Set DEFAULT_FORWARD_POLICY config if it doesn't already exist
#    lineinfile: dest=/etc/default/docker line="DEFAULT_FORWARD_POLICY=\"DROP\""
#    when: test_default_forward_policy.stdout == ""
#    become: true

  - name: Update ufw after.rules with nat update if not already present
    blockinfile:
      path: /etc/ufw/after.rules
      marker: "## {mark} DOCKER and UFW rules added by ansible configuration"
      backup: yes
      insertbefore: BOF
      block: |
        *filter
        :ufw-user-forward - [0:0]
        :DOCKER-USER - [0:0]
        -A DOCKER-USER -j RETURN -s 10.0.0.0/8
        -A DOCKER-USER -j RETURN -s 172.17.0.0/12
        -A DOCKER-USER -j RETURN -s 192.168.0.0/16

        -A DOCKER-USER -j ufw-user-forward

        -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
        -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
        -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.17.0.0/12
        -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
        -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
        -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 172.17.0.0/12

        -A DOCKER-USER -j RETURN
        COMMIT
    become: true

  - name: ufw reload
    ufw:
      state: reloaded
    become: true

  - name: docker reload
    service:
      name: docker
      state: restarted
    become: true

  - name: docker-compose build for bardly project
    shell: "docker-compose build"
    args:
      chdir: "/home/{{ansible_ssh_user}}/projects/bardly"
    tags:
      - docker

  - name: docker-compose up for bardly project
    shell: "docker-compose up"
    args:
      chdir: "/home/{{ansible_ssh_user}}/projects/bardly"
    async: 1000
    poll: 0
    tags:
      - docker

