---

  # checkout git project. Uses https as we only need read access and dont want to manage ssh keys
  - name: Clone bardly git repo to users /projects/bardly directory. Defaults to master branch.
    git:
      repo: https://github.com/leachuk/writeon-mvp-step1.git
      dest: ~/projects/bardly
    tags:
      - git
