---
  - name: ufw enabled and set initial deny all
    ufw:
      state: enabled
      policy: deny
    become: true

  - name: ufw allow ssh
    ufw:
      rule: allow
      name: OpenSSH
    become: true

  - name: ufw allow all on bardly api app port
    ufw:
      rule: allow
      port: 9000
    become: true

#  - name: ufw open couchdb port for testing
#    ufw:
#      rule: allow
#      port: 5984
#    become: true
