---
#  - name: Say hi
#    tags: foo
#    shell: echo "hi..."
#    register: hello
#
#  - debug: msg="{{ hello.stdout }}"

  - name: ufw allow us (104.207.151.30) to accept au (108.61.251.93) couchdb port for replication
    ufw:
      rule: allow
      src: 108.61.251.93
      to_port: 5984
    become: true
